#!/usr/bin/env ruby

require 'thor'
require 'mysql_log_tools.rb'

class App < Thor
  package_name "MySQL Log"

  desc "queries [logfile]", "List queries"
  option :format, :desc => "Query format",
      :type => :string, :default => "raw", :aliases => "-f",
      :enum => %w(raw short abstract)
  def queries(filename = "/dev/stdin")
    MysqlLogTools.list_queries(filename, options[:format].to_sym)
  end

  desc "abstract-queries [logfile]", "List abstract queries in log file"
  def abstract_queries(filename = "/dev/stdin")
    MysqlLogTools.list_queries(filename, :abstract)
  end
end

App.start
