#!/usr/bin/env ruby

require 'thor'
require 'mysql_log_tools.rb'

class App < Thor
  package_name "MySQL Log"

  desc "list [logfile]", "List logfile entries"
  option :format, :desc => "Query format",
      :type => :string, :default => "raw", :aliases => "-f",
      :enum => %w(raw short abstract)
  def list(filename = "/dev/stdin")
    MysqlLogTools.list(filename, options[:format].to_sym)
  end

  desc "queries [logfile]", "List queries"
  def queries(filename = "/dev/stdin")
    MysqlLogTools.list_queries(filename)
  end
end

App.start
